### ISSUE TITLE
serial property that waits for input

### ISSUE THREAD

**Issue by hbrylkowski** [obestwalter/pew3wm#1]
https://github.com/adafruit/circuitpython/pull/1193

**Comment by ultrabug** [comment]
@hbrylkowski we got everything working in both directions! code is up to date :D

It's awesome! @obestwalter did a video, he'll post it soon :+1: 

Thanks again for your time, help and enthusiasm mate!

**Comment by obestwalter** [comment]
Updated the [readme](https://github.com/obestwalter/pew3wm/blob/master/README.md) with a link:  - hopefully we can make a nicer video at some point :)

**Comment by objarni** [comment]
Nice cleanup!

**Comment by ultrabug** [comment]
Awesome @obestwalter thanks!

@hbrylkowski hope you like it :)
